### ISSUE TITLE
Lost on login startup

### ISSUE THREAD

**Issue by Coalms** [LordRusk/gocaudices#2]
I don't know if I am confused with the readme or a problem with the script or my system,no matter running this from any veriation of .profile,autostart.sh patch for dwm with our without tsp with all of the above*
but as soon as i login and run it by myself through the terminal everythin's fine,
Just in case I also checked if I have multiple versions installed but that ain't it,im confused at this point

tsp:(helps "stabilize"baddly setup startups of programs,or thats what I have noticed in the past)

**Comment by LordRusk** [comment]
Hey, thanks for using this little project of mine! What way are you starting it? `gocaudices` or `gocaudices &`?

My guess, is that it tries to start it *before* xorg is running, and since xgb connects to X, if it isn't started, the xgb will fail to connect. A solution might be to do something like I do. check my [.zprofile](https://github.com/LordRusk/artixdwm/blob/master/.zprofile) and my [.xprofile](https://github.com/LordRusk/artixdwm/blob/master/.xprofile) for details. Let me know if this works!

**Comment by Coalms** [comment]
> `gocaudices`

gocaudices &

or nohup gocaudices &

sleep 2 && gocaudices &

also i tried to put it last in my .profile or .xprofile ,even after a sleep && but to no avail , I am still confused as to why this happens,like stated before even running it through tsp like so 
tsp gocaudices &
or
nohup tsp gocaudices &
or
sleep 3 && (any of the above) 
give an error similar to "ts could not run the program",
im confused if I am missing something on how go works,
I should be able to try and test it tomorrow on a friends computer and compare the 2 devices to see what I have done differently
I should update you by then,but untill then I am questioning it

**Comment by Coalms** [comment]
gocaudices &

or nohup gocaudices &

sleep 2 && gocaudices &

also i tried to put it last in my .profile or .xprofile ,even after a sleep && but to no avail , I am still confused as to why this happens,like stated before even running it through tsp like so
tsp gocaudices &
or
nohup tsp gocaudices &
or
sleep 3 && (any of the above)
give an error similar to "ts could not run the program",
im confused if I am missing something on how go works,
I should be able to try and test it tomorrow on a friends computer and compare the 2 devices to see what I have done differently
I should update you by then,but untill then I am questioning it

**Comment by Coalms** [comment]
missclicked close comment (⌒_⌒;)

**Comment by LordRusk** [comment]
I'm baffled by this as well, with the go.mod it should be installing everything correctly and as needed. When you do test tomorrow, perhaps run put something like `gocaudices > ~/output` and read what the output is, which should help us come to a better understanding of what exactly is failing.

**Comment by Coalms** [comment]
Ugh..I...Im embarrassed to say that rather than writing export PATH=$HOME..... i did export PATH+$HOME.... my disappointment at this IQ drop is immeasurable and my day is ruined,

I deserve the gulag... （/∇＼; ）

**Comment by Coalms** [comment]
After careful consideration I plea for ya to delete this,I feel ashamed

**Comment by LordRusk** [comment]
A fail isn't bad, without failing, you will never know how to succeed. Don't worry, i've done much much worse and embarrised myself even more when contributing to libs and having issues. 9/10 the issues are just tunnel vision, but without reaching out to someone with a different perspective, you'll never lose your tunnel vision.

Thank you for using this little projct, and I hope it treats you well! :)
